name: Cleanup Build Cache

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      keep_count:
        description: 'Number of untagged versions to keep (0 = delete all - use with caution!)'
        required: true
        default: '3'
        type: choice
        options:
        - '3'
        - '5'
        - '10'
        - '0'

permissions:
  packages: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old untagged container images
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'codex-python'
        package-type: 'container'
        min-versions-to-keep: ${{ inputs.keep_count || '3' }}
        delete-only-untagged-versions: true
        token: ${{ secrets.GITHUB_TOKEN }}
